language: go
go:
- 1.11
install:
- go get github.com/mattn/goveralls
- go get -u golang.org/x/lint/golint
script:
- make test
# - make vet
# - make test-short
# - make test-long
# - make coverage-send
